spring:
  # thymeleaf
  thymeleaf:
    prefix: classpath:templates/thymeleaf/
    suffix: .html
    cache: false
    check-template-location: true
  # security
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:80/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: 
              - profile_nickname
              - account_email 
            client-name: Kakao
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:80/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: 
              - name
              - email
            client-name: Naver
  servlet:
    # file upload
    multipart:
      max-file-size: 200MB
      enabled: 'true'
      max-request-size: 215MB
      file-size-threshold: 2KB
  # Oracle Data
  datasource:
    url: jdbc:oracle:thin:@${DB_IP}:1521/xe
    username: ${DB_ID}
    password: ${DB_PWD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        format_sql: true
logging:
  level: 
    org.hibernate.SQL: debug
server:
  port: '80'